environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    RUST_CHANNEL: nightly
    WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
  - TARGET: i686-pc-windows-msvc
    RUST_CHANNEL: nightly
    WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/Packet.lib"
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"

install:
  - ps: mkdir C:/dl
  - curl -o "C:/dl/wpd.zip" "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip"
  - ps: Add-Type -AssemblyName system.io.compression.filesystem
  - ps: "[io.compression.zipfile]::ExtractToDirectory(\"C:/dl/wpd.zip\", \"C:/dl/wpdpack\")"
  - ps: mkdir ${env:APPVEYOR_BUILD_FOLDER}/lib
  - ps: cp ${env:WPD_LIB_PATH} ${env:APPVEYOR_BUILD_FOLDER}/lib
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - call "%VCVARS%"
  - choco install winpcap
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --verbose --all
  - cargo test --verbose --all
